services:
  agent:
    build:
      context: ./vps-metrics-agent
    container_name: vps-agent
    ports:
      - "9101:9101"
    restart: unless-stopped

  server:
    build:
      context: ./vps-status-backend
    container_name: vps-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - agent
  
  frontend:
    build:
      context: ./vps-status-frontend
    container_name: vps-frontend
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - server

networks:
  default:
    driver: bridge
