services:
  server:
    build:
      context: .
    container_name: vps-backend-standalone
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/usr/src/app/config.json:ro
    restart: unless-stopped

networks:
  default:
    driver: bridge
