services:
  frontend:
    build:
      context: . # Build context is the current directory
      # VITE_API_URL will be read from the .env file during the build process inside Dockerfile
    container_name: vps-frontend-standalone # Unique name for standalone frontend
    ports:
      - "3001:3001" # Map host port 3001 to container port 3001
    restart: unless-stopped
    # Environment variable is not needed at runtime as it's baked into the build
    # Note: Ensure your .env file in this directory has the correct VITE_API_URL
    # before running 'docker-compose build' or 'docker-compose up --build'.

networks:
  default:
    driver: bridge
