services:
  frontend:
    build:
      context: . # Build context is the current directory
      args:
        - VITE_API_URL=${VITE_API_URL:-http://server:3000/api/vps-status} # Default value if not provided
    container_name: vps-frontend-standalone # Unique name for standalone frontend
    ports:
      - "3001:3001" # Map host port 3001 to container port 3001
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://server:3000/api/vps-status} # Can be overridden when running docker-compose
    # Note: You can override the API URL by setting the VITE_API_URL environment variable:
    # VITE_API_URL=http://your-backend-url:3000/api/vps-status docker-compose up -d

networks:
  default:
    driver: bridge
